### ISSUE TITLE
NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by bapedersen** [ta4j/ta4j#148]
`Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at eu.verdelhan.ta4j.BaseTimeSeries.<init>(BaseTimeSeries.java:41)
	at eu.verdelhan.ta4j.BaseTimeSeries.<init>(BaseTimeSeries.java:86)
	at eu.verdelhan.ta4j.BaseTimeSeries.<init>(BaseTimeSeries.java:77)
	at com.company.CandlestickList.asTimeSeries(CandlestickList.java:22)
	at com.company.Main.main(Main.java:38)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more`

**Comment by bapedersen** [comment]
Installed it wrong. Nevermind
