### ISSUE TITLE
IndexOutOfBoundsException in PivotPointIndicator

### ISSUE THREAD

**Issue by oxofrembl** [ta4j/ta4j#268]
I receive an IndexOutOfBoundsException in PivotPointIndicator with Day as timeLevel parameter.

```
23:19:36,502 ERROR [stderr] (default task-9) java.lang.IndexOutOfBoundsException: Size of series: 575 bars, 0 bars removed, index = -1
23:19:36,503 ERROR [stderr] (default task-9) 	at org.ta4j.core.BaseTimeSeries.getBar(BaseTimeSeries.java:183)
23:19:36,503 ERROR [stderr] (default task-9) 	at org.ta4j.core.indicators.pivotpoints.PivotPointIndicator.getPreviousPeriod(PivotPointIndicator.java:122)
23:19:36,503 ERROR [stderr] (default task-9) 	at org.ta4j.core.indicators.pivotpoints.PivotPointIndicator.getBarsOfPreviousPeriod(PivotPointIndicator.java:109)
23:19:36,503 ERROR [stderr] (default task-9) 	at org.ta4j.core.indicators.pivotpoints.PivotPointIndicator.calculate(PivotPointIndicator.java:66)
23:19:36,503 ERROR [stderr] (default task-9) 	at org.ta4j.core.indicators.pivotpoints.PivotPointIndicator.calculate(PivotPointIndicator.java:39)
23:19:36,503 ERROR [stderr] (default task-9) 	at org.ta4j.core.indicators.CachedIndicator.getValue(CachedIndicator.java:99)
23:19:36,504 ERROR [stderr] (default task-9) 	at org.ta4j.core.indicators.RecursiveCachedIndicator.getValue(RecursiveCachedIndicator.java:81)
23:19:36,504 ERROR [stderr] (default task-9) 	at org.ta4j.core.trading.rules.OverIndicatorRule.isSatisfied(OverIndicatorRule.java:63)
23:19:36,504 ERROR [stderr] (default task-9) 	at org.ta4j.core.Strategy.shouldEnter(Strategy.java:129)
23:19:36,504 ERROR [stderr] (default task-9) 	at org.ta4j.core.BaseStrategy.shouldEnter(BaseStrategy.java:137)
```

**Comment by team172011** [comment]
Hi @oxofrembl ,
Can you please provide example code?
