### ISSUE TITLE
ClassCastException in BigDecimalNum on latest SNAPSHOT

### ISSUE THREAD

**Issue by laxika** [ta4j/ta4j#291]
Hello guys,

I'm trying to calculate my profit like this:

```
            AnalysisCriterion vsBuyAndHold = new VersusBuyAndHoldCriterion(new TotalProfitCriterion());
            System.out.println("Our profit vs buy-and-hold profit: " + vsBuyAndHold.calculate(timeSeries, tradingRecord));
```

But I keep getting this exception:

```
java.lang.ClassCastException: org.ta4j.core.num.DoubleNum cannot be cast to org.ta4j.core.num.BigDecimalNum
	at org.ta4j.core.num.BigDecimalNum.multipliedBy(BigDecimalNum.java:126) ~[ta4j-core-0.12-SNAPSHOT.jar:na]
	at org.ta4j.core.analysis.criteria.TotalProfitCriterion.lambda$calculate$1(TotalProfitCriterion.java:42) ~[ta4j-core-0.12-SNAPSHOT.jar:na]
	at java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80) ~[na:1.8.0_171]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_171]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_171]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_171]
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:474) ~[na:1.8.0_171]
	at org.ta4j.core.analysis.criteria.TotalProfitCriterion.calculate(TotalProfitCriterion.java:42) ~[ta4j-core-0.12-SNAPSHOT.jar:na]
	at org.ta4j.core.analysis.criteria.VersusBuyAndHoldCriterion.calculate(VersusBuyAndHoldCriterion.java:52) ~[ta4j-core-0.12-SNAPSHOT.jar:na]
	at com.morethanheroic.bitcointrader.scheduler.TraderUpdater.updateTrader(TraderUpdater.java:121) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
```

Do anybody have any idea why is this happening? I highly suspect that this is a bug.

**Comment by team172011** [comment]
This is because the String.format function formats the value country-specific and I get in the `PrecisionNum#sqrt` function at line 280:
`String string = String.format("%1.1e", estimate);` =>  estimate = 3.0E... string = 3,0E

**Comment by team172011** [comment]
Changing to 
`String string = String.format(Locale.ROOT,"%1.1e", estimate);`
will fix it

**Comment by team172011** [comment]
@laxika If I add the follwoing test to VersusBuyAndHoldCriterionTest.java of the current develop branch it will pass:

```
    @Test
    public void calculateWithTotalProfit(){
        BaseTimeSeries.SeriesBuilder builder = new BaseTimeSeries.SeriesBuilder();
        TimeSeries series = builder.withNumTypeOf(numFunction).build();
        series.addBar(ZonedDateTime.now(),100,100,100,100);
        series.addBar(ZonedDateTime.now().plusSeconds(1),100,100,100,100);
        series.addBar(ZonedDateTime.now().plusSeconds(2),100,100,100,100);
        series.addBar(ZonedDateTime.now().plusSeconds(3),100,100,100,100);
        series.addBar(ZonedDateTime.now().plusSeconds(4),100,100,100,100);
        series.addBar(ZonedDateTime.now().plusSeconds(5),100,100,100,100);
        series.addBar(ZonedDateTime.now().plusSeconds(6),100,100,100,100);
        TradingRecord tradingRecord = new BaseTradingRecord(
                Order.buyAt(0, NaN, NaN), Order.sellAt(1, NaN, NaN),
                Order.buyAt(2, NaN, NaN), Order.sellAt(5, NaN, NaN));
        TotalProfitCriterion totalProfitCriterion = new TotalProfitCriterion();
        AnalysisCriterion buyAndHold = new VersusBuyAndHoldCriterion(totalProfitCriterion);
        buyAndHold.calculate(series,tradingRecord);
    }
```
maybe the 0.12-SNAPSHOT (it is a little bit older than the current develop) has a bug that already has been fixed in develop. After merging #292 I will update the SNAPSHOT

**Comment by team172011** [comment]
fixed
