### ISSUE TITLE
Issue serializing BaseTimeSeries 

### ISSUE THREAD

**Issue by wlk** [ta4j/ta4j#370]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
I'm trying to use ta4j together with Apache spark and running into issues when I'm sending instances of `BaseTimeSeries` between the nodes.

```
Exception in thread "main" java.io.NotSerializableException: org.ta4j.core.num.PrecisionNum$$Lambda$1177/979719862
Serialization stack:
        - object not serializable (class: org.ta4j.core.num.PrecisionNum$$Lambda$1177/979719862, value: org.ta4j.core.num.PrecisionNum$$Lambda$1177/979719862@351d93bd)
        - field (class: org.ta4j.core.BaseTimeSeries, name: numFunction, type: interface java.util.function.Function)
        - object (class org.ta4j.core.BaseTimeSeries, org.ta4j.core.BaseTimeSeries@19ec5357)
        at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:41)
        at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
        at org.apache.spark.broadcast.TorrentBroadcast$.$anonfun$blockifyObject$4(TorrentBroadcast.scala:291)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.broadcast.TorrentBroadcast$.blockifyObject(TorrentBroadcast.scala:293)
        at org.apache.spark.broadcast.TorrentBroadcast.writeBlocks(TorrentBroadcast.scala:127)
        at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:88)
        at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:34)
        at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:62)
        at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1489)
```

To be more specific I'm sending a complete instance of `BaseTimeSeries` but the failure is when seralizing `numFunction` which is `java.util.function.Function`.

I'm using OpenJDK 11.

Please let me know if this is something that can be fixed in `ta4j` directly or indirectly (like for example doing something with `numFunction`) or is this out of scope for this project. 

**To Reproduce**
1. Serialize an instance of `BaseTimeSeries`
2. Send it as a broadcast variable

**Expected behavior**
`BaseTimeSeries` should be serialized

**Additional context**
As a workaround I'm creating a `List[Bar]` and sending it between nodes which works fine (each node is redoing the same work of creating `BaseTimeSeries` from the list over and over again though)

**Comment by nimo23** [comment]
hello @wlk sorry that no one answered you so far. I think, now you can serialize without problems. I hope it helps: https://github.com/ta4j/ta4j/pull/657

**Comment by wlk** [comment]
@nimo23 Thank you :)

**Comment by nimo23** [comment]
@team172011  please close this issue (resolved).
