### ISSUE TITLE
Error with BarSeries

### ISSUE THREAD

**Issue by udarnick** [ta4j/ta4j#599]
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

If possible provide a **[minimal working example](https://stackoverflow.com/help/mcve)**!

Could you explain what I am doing wrong.  This is in a live trading scenario:

`							Map<String, ArrayList<Bar>> bars;
							bars = alpacaAPI.getBars(BarsTimeFrame.FIVE_MINUTE, stocksOver5DTO.getSymbol(), 200, start, end, null, null);
							if (bars.size() >0) {
								bars.forEach(
										(string, barArrayList) -> {
//											barArrayList.sort(Comparator.comparing(Bar::getT).reversed());
											Collections.reverse(barArrayList);
											if(barArrayList.get(0).getC().compareTo(5.00) >0) {
												barArrayList.forEach(
														bar -> {
															ZonedDateTime time = ZonedDateTime.ofInstant(Instant.ofEpochSecond(bar.getT()), ZoneId.of("America/New_York"));
															seriesPH.addBar(time, bar.getO(), bar.getH(), bar.getL(), bar.getC(), bar.getV());
														}
												);
											}
										}
								);`

Error is:  

`
2020-06-01 15:22:37.506  INFO 99040 --- [ool-2-thread-13] com.boivin.trading.Trade                 : qualifyTrade symbol AAL
Exception in thread "pool-2-thread-13" java.lang.IllegalArgumentException: Cannot add a bar with end time:2020-06-01T11:40-04:00[America/New_York] that is <= to series end time: 2020-06-01T11:40-04:00[America/New_York]
	at org.ta4j.core.BaseBarSeries.addBar(BaseBarSeries.java:404)
	at org.ta4j.core.BarSeries.addBar(BarSeries.java:159)
	at org.ta4j.core.BaseBarSeries.addBar(BaseBarSeries.java:425)
	at org.ta4j.core.BarSeries.addBar(BarSeries.java:195)
	at com.boivin.trading.Trade.lambda$qualifyTrade$3(Trade.java:154)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at com.boivin.trading.Trade.lambda$qualifyTrade$4(Trade.java:151)
	at java.base/java.util.Map.forEach(Map.java:661)
	at com.boivin.trading.Trade.lambda$qualifyTrade$6(Trade.java:147)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at com.boivin.trading.Trade.qualifyTrade(Trade.java:139)
	at com.boivin.trading.TradeExecutor$2.run(TradeExecutor.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
`

Thank you.

**Comment by udarnick** [comment]
I think I see my problem.  I can only do one stock at a time.  I am going to revise my code and that works, I will close this.

**Comment by udarnick** [comment]
I got it fixed.  Silly me.
