### ISSUE TITLE
[BUG] ParabolicSarIndicator NullPointerException error

### ISSUE THREAD

**Issue by regueira** [ta4j/ta4j#793]
**Describe the bug**
When the PSAR trend changes, the variable `minMaxExtremePoint` is null.

**To Reproduce**
1. Use PSAR indicator.
2. Wait for a trend change up or down.
3. Check the variable `minMaxExtremePoint` isn't initialized 

```
java.lang.NullPointerException: null
	at org.ta4j.core.num.DecimalNum.isLessThan(DecimalNum.java:671) ~[ta4j-core-0.14.jar:na]
	at org.ta4j.core.indicators.ParabolicSarIndicator.calculate(ParabolicSarIndicator.java:165) ~[ta4j-core-0.14.jar:na]
	at org.ta4j.core.indicators.ParabolicSarIndicator.calculate(ParabolicSarIndicator.java:44) ~[ta4j-core-0.14.jar:na]
	at org.ta4j.core.indicators.CachedIndicator.getValue(CachedIndicator.java:119) ~[ta4j-core-0.14.jar:na]
	at org.ta4j.core.indicators.RecursiveCachedIndicator.getValue(RecursiveCachedIndicator.java:78) ~[ta4j-core-0.14.jar:na]
	at org.ta4j.core.rules.UnderIndicatorRule.isSatisfied(UnderIndicatorRule.java:81) ~[ta4j-core-0.14.jar:na]
	at org.ta4j.core.rules.AndRule.isSatisfied(AndRule.java:53) ~[ta4j-core-0.14.jar:na]
	at org.ta4j.core.rules.OrRule.isSatisfied(OrRule.java:53) ~[ta4j-core-0.14.jar:na]
	at org.ta4j.core.Strategy.shouldEnter(Strategy.java:130) ~[ta4j-core-0.14.jar:na]
	at org.ta4j.core.BaseStrategy.shouldEnter(BaseStrategy.java:144) ~[ta4j-core-0.14.jar:na]
```

**Comment by team172011** [comment]
Hi @regueira can you please provide a working example with bar series?

**Comment by qiuranke** [comment]
**Describe the bug**
on 0.15

java.lang.NullPointerException: null
        at org.ta4j.core.num.DoubleNum.isLessThan(DoubleNum.java:240)
        at org.ta4j.core.indicators.ParabolicSarIndicator.calculate(ParabolicSarIndicator.java:166)
        at org.ta4j.core.indicators.ParabolicSarIndicator.calculate(ParabolicSarIndicator.java:44)
        at org.ta4j.core.indicators.CachedIndicator.getValue(CachedIndicator.java:123)
        at org.ta4j.core.indicators.RecursiveCachedIndicator.getValue(RecursiveCachedIndicator.java:78)
**To Reproduce**
set BarSeries MaximumBarCount

removeExceedingBars() called 

the variable minMaxExtremePoint is null
