### ISSUE TITLE
[BUG] Strategy should enter/exit for BarSeries.setMaximumBarCount() throws exception after adding new bar 

### ISSUE THREAD

**Issue by sergiugit** [ta4j/ta4j#828]
I do not know if this is correct or not but series.getEndIndex() increses when I add a new bar and check strategy should enter/exit I got this error:

java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 30
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.ta4j.core.indicators.CachedIndicator.getValue(CachedIndicator.java:124)
	at org.ta4j.core.indicators.RecursiveCachedIndicator.getValue(RecursiveCachedIndicator.java:84)
....................

There is the Parabolic Sar in the entry/exit rules.

**Comment by johnthetireless** [comment]
do you have a trailing stop rule?

**Comment by team172011** [comment]
Hi @sergiugit can you please provide a minimal working example?

**Comment by sergiugit** [comment]
I was not able to extract the code from my project into an example. I also found an issue in my code: I had 1m period and I was adding 5m period bars after. I also tried this but not able to replicate the error in dummy example.

**Comment by sergiugit** [comment]
It is not a ta4j issue. By error I reinitialized the barseries and strategy twice. Then I added a new bar in one and called should enter/exit on other. As the indexes are scrambled after the 'add' method I got the OutofBounds exception in the cached indicator.

**Comment by team172011** [comment]
okay, that's why I am always asking for a reproducible example before spending time on analyzing and debugging :-)
